#python normalize_mean_std.py --train_hdf5 /srv/scratch/annashch/deeplearning/dmso/inputs/s_by_m_by_pos/dmso.train.hdf5 --test_hdf5 /srv/scratch/annashch/deeplearning/dmso/inputs/s_by_m_by_pos/dmso.test.hdf5 --valid_hdf5 /srv/scratch/annashch/deeplearning/dmso/inputs/s_by_m_by_pos/dmso.validate.hdf5 --out_normalized_train_hdf5 /srv/scratch/annashch/deeplearning/dmso/inputs/s_by_m_by_pos/normalized.dmso.train.hdf5 --out_normalized_valid_hdf5 /srv/scratch/annashch/deeplearning/dmso/inputs/s_by_m_by_pos/normalized.dmso.valid.hdf5 --out_normalized_test_hdf5 /srv/scratch/annashch/deeplearning/dmso/inputs/s_by_m_by_pos/normalized.dmso.test.hdf5

#GECCO positional
#python normalize_mean_std.py --train_hdf5 /srv/scratch/annashch/deeplearning/gecco/inputs/s_by_m_by_pos/gecco.train.hdf5 --test_hdf5 /srv/scratch/annashch/deeplearning/gecco/inputs/s_by_m_by_pos/gecco.test.hdf5 --valid_hdf5 /srv/scratch/annashch/deeplearning/gecco/inputs/s_by_m_by_pos/gecco.validate.hdf5 --out_normalized_train_hdf5 /srv/scratch/annashch/deeplearning/gecco/inputs/s_by_m_by_pos/normalized.gecco.train.hdf5 --out_normalized_valid_hdf5 /srv/scratch/annashch/deeplearning/gecco/inputs/s_by_m_by_pos/normalized.gecco.valid.hdf5 --out_normalized_test_hdf5 /srv/scratch/annashch/deeplearning/gecco/inputs/s_by_m_by_pos/normalized.gecco.test.hdf5 --out_means gecco.means.npy --out_std gecco.std.npy

#GECCO non-positional 
#python normalize_mean_std.py --train_hdf5 /srv/scratch/annashch/deeplearning/gecco/inputs/s_by_m/gecco.train.hdf5 --test_hdf5 /srv/scratch/annashch/deeplearning/gecco/inputs/s_by_m/gecco.test.hdf5 --valid_hdf5 /srv/scratch/annashch/deeplearning/gecco/inputs/s_by_m/gecco.validate.hdf5 --out_normalized_train_hdf5 /srv/scratch/annashch/deeplearning/gecco/inputs/s_by_m/normalized.gecco.train.hdf5 --out_normalized_valid_hdf5 /srv/scratch/annashch/deeplearning/gecco/inputs/s_by_m/normalized.gecco.valid.hdf5 --out_normalized_test_hdf5 /srv/scratch/annashch/deeplearning/gecco/inputs/s_by_m/normalized.gecco.test.hdf5 --out_means gecco.means.npy --out_std gecco.std.npy


#heterokaryon
#python normalize_mean_std.py --train_hdf5 /srv/scratch/annashch/deeplearning/heterokaryon/inputs/s_by_m_by_pos/het.train.hdf5 --test_hdf5 /srv/scratch/annashch/deeplearning/heterokaryon/inputs/s_by_m_by_pos/het.test.hdf5 --valid_hdf5 /srv/scratch/annashch/deeplearning/heterokaryon/inputs/s_by_m_by_pos/het.validate.hdf5 --out_normalized_train_hdf5 /srv/scratch/annashch/deeplearning/heterokaryon/inputs/s_by_m_by_pos/normalized.het.train.hdf5 --out_normalized_valid_hdf5 /srv/scratch/annashch/deeplearning/heterokaryon/inputs/s_by_m_by_pos/normalized.het.valid.hdf5 --out_normalized_test_hdf5 /srv/scratch/annashch/deeplearning/heterokaryon/inputs/s_by_m_by_pos/normalized.het.test.hdf5 --out_means het.means.npy --out_std het.std.npy

#python normalize_mean_std.py --train_hdf5 gecco.deeplift.vars.hdf5  --out_normalized_train_hdf5 normalized.gecco.deeplift.vars.hdf5  --out_means gecco.deeplift.var.means.npy --out_std gecco.deeplift.var.var.npy

python normalize_mean_std.py --train_hdf5 anna_positional.hdf5  --out_normalized_train_hdf5 normalized.anna_positional.hdf5  --out_means gecco.deeplift.var.means.npy --out_std gecco.deeplift.var.var.npy
